version: '3.8'

services:
  # ===== COMMON SERVICES =====
  postgres:
    image: postgres:15-alpine
    container_name: interview_postgres
    environment:
      POSTGRES_DB: interview_db
      POSTGRES_USER: interview_user
      POSTGRES_PASSWORD: interview_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U interview_user -d interview_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - interview_network

  redis:
    image: redis:7-alpine
    container_name: interview_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - interview_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  interview_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 